{{- if not .Values.global.jwtExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-jwt
  labels:
    {{- include "cp.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.global.jwtSecret | quote }}
{{- end }}
{{- if not .Values.global.postgres.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres
  labels:
    {{- include "cp.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.global.postgres.existingSecretPasswordKey }}: {{ .Values.global.postgres.password | quote }}
{{- end }}
